# Generated by Django 4.2.20 on 2025-04-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='updates',
            field=models.TextField(blank=True),
        ),
    ]
